// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Call as $Call, Create as $Create} from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function APICall(urlStr: string, method: string, headers: $models.Header[], formData: $models.FormData[], isAPIKey: boolean, APIKey: string): Promise<string> & { cancel(): void } {
    let $resultPromise = $Call.ByID(2641746452, urlStr, method, headers, formData, isAPIKey, APIKey) as any;
    return $resultPromise;
}
