// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Create as $Create} from "@wailsio/runtime";

export class FormData {
    "Key": string;
    "Value": string;

    /** Creates a new FormData instance. */
    constructor($$source: Partial<FormData> = {}) {
        if (!("Key" in $$source)) {
            this["Key"] = "";
        }
        if (!("Value" in $$source)) {
            this["Value"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FormData instance from a string or object.
     */
    static createFrom($$source: any = {}): FormData {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FormData($$parsedSource as Partial<FormData>);
    }
}

export class Header {
    "Name": string;
    "Value": string;

    /** Creates a new Header instance. */
    constructor($$source: Partial<Header> = {}) {
        if (!("Name" in $$source)) {
            this["Name"] = "";
        }
        if (!("Value" in $$source)) {
            this["Value"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Header instance from a string or object.
     */
    static createFrom($$source: any = {}): Header {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Header($$parsedSource as Partial<Header>);
    }
}
